name: schedule_check_pr_dev2branch_by_cron

on:
  push:
    branches:
      - develop
# on:
#  schedule:
#    - cron: "0 * * * *"

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - shell: bash
        id: chk_vers
        run: |
          echo "::set-output name=current_vers_check::`./scripts/start.sh ${{ secrets.NODOSIT }} ${{ secrets.NODOUAT }} ${{ secrets.NODOPROD }}`"
          echo "::set-output name=current_vers_check_res::`echo &?"
      - shell: bash
        run: |
          echo "Check result >>>${{ steps.chk_vers.outputs.current_vers_check_res }}<<<"

      # - if: steps.chk_vers.outputs.current_vers_check_res == 1
      #   name: Crete pull-request and automerge
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     source_branch: develop
      #     destination_branch: "develop" # If blank, default: master
      #     pr_title: "Update version file repo after new NodoSPC realese in SIT,UAT or PROD with new pagopa-api definitions" # Title of pull request
      #     pr_label: "automerge, UPD_VERS_ENV_REPO" # Comma-separated list (no spaces)
      #     pr_assignee: "pagopa-team" # Comma-separated list (no spaces)
      #     pr_allow_empty: true # Creates pull request even if there are no changes
      #     github_token: ${{ secrets.ALLOW_CLONE }} #

      - if: steps.chk_vers.outputs.current_vers_check_res == 1
        name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "PagoPa-API"
          SLACK_ICON: https://www.pagopa.gov.it/assets/images/pagopa-logo.png?size=48