name: schedule_check_pr_dev2branch_by_cron

on:
  push:
    branches:
      - develop
# on:
#  schedule:
#    - cron: "0 * * * *"

jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - shell: bash
        id: chk_vers
        run: |
          echo "::set-output name=current_vers_check_res::`./scripts/start.sh ${{ secrets.NODOSIT }} ${{ secrets.NODOUAT }} ${{ secrets.NODOPROD }}`"
      - shell: bash
        run: |
          echo "Check-----------${{ steps.chk_vers.outputs.current_vers_check_res }}-"
      - if: steps.chk_vers.outputs.current_vers_check_res == 1
        name: Update version file
        run: git config user.email "pagopateam" && git config --global user.name "pagopateam" && git add ./scripts/resources/vers.txt && git commit -a -m "update file environments version" && git push

      - if: steps.chk_vers.outputs.current_vers_check_res == 1
        name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "PagoPa-API"
          SLACK_ICON: https://www.pagopa.gov.it/assets/images/pagopa-logo.png?size=48